project_id = "gfrpkapmievifpqfhjrp"

[functions.create-trainer-account]
verify_jwt = false

[functions.send-admin-welcome-email]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.seed-demo-accounts]
verify_jwt = false
